Component mobile - Feed cards & pill buttons
poop-team/project-monorepo pull request #46
Opened 2022-10-24 21:50 UTC by kitorer

2022-10-24 23:21 UTC, rob-3 requested changes
I see what you're doing with the slightly different classnames. I would just make one `Button` that does `...items-center justify-center ${props.className}` in a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) at the end.

2022-10-24 23:21 UTC, rob-3 commented on mobile/src/components/Button.tsx
> +function ButtonPill(props) {
I prefer `function ButtonPill({ name }) {` here and then just `name` below.

2022-10-24 23:21 UTC, rob-3 commented on mobile/src/components/Button.tsx
> +function ButtonRounded(props) {
Same as above

2022-10-25 01:15 UTC, Rikimbili commented on mobile/src/components/Button.tsx
> +    <Pressable className= "rounded-md bg-[#2D1C70] opacity-95 h-7 items-center justify-center" >
For the colors I think it is good practice to use predefined colors. Currently for web we are using slate and indigo colors included in tailwind (No need to extend the theme in the config file). 

This way you can easily pick the shade too (In this case it'd be something like bg-indigo-600)

2022-10-25 20:57 UTC, rob-3 requested changes

2022-10-25 20:57 UTC, rob-3 commented on mobile/src/components/Button.tsx
> +  pilled ? baseStyle += ' rounded-full' : baseStyle += ' rounded-md';
Any reason you're using one style here for disabled and another for pilled?

2022-10-25 20:57 UTC, rob-3 commented on mobile/src/components/Button.tsx
> +*/
This should start with `/**` to help editors pick it up as a docstring. You should also prepend each line with `*` and indent it so the `*`s line up.

```ts
/**
 * @param name - name of the button
 * @param addButtonStyle - add custom style to the button
 * @param addTextStyle - add custom style to the text
 * @param pilled - make the button pilled
 */
```

2022-10-25 22:09 UTC, rob-3 requested changes
Looks good, just run prettier on this if you can and I'll be happy to approve

2022-10-25 23:06 UTC, rob-3 approved these changes

2022-10-26 02:12 UTC, merged