Add create collection api endpoint
poop-team/project-monorepo pull request #49
Opened 2022-10-25 23:16 UTC by Aaronel10

2022-10-25 23:20 UTC, Sleepingpirates approved these changes

2022-10-25 23:20 UTC, Sleepingpirates commented on web/src/pages/api/addPostToCollection.ts
> +        connect: { id: postToAdd.id },
Good job with the connect here

2022-10-25 23:35 UTC, rob-3 requested changes
Just a few minor changes - I also am not certain, but I think that you don't have to return in Next.js, ie I think just `res.json()` is sufficient instead of `return res.json`

2022-10-25 23:35 UTC, rob-3 commented on web/src/pages/api/addPostToCollection.ts
> +      id: String(postId),
I would suggest `postId.toString()`, which will throw if postId is null or undefined somehow

2022-10-25 23:35 UTC, rob-3 commented on web/src/pages/api/addPostToCollection.ts
> +  return res.json({ sucess: true });
`success`

2022-10-25 23:35 UTC, rob-3 commented on web/src/pages/api/addPostToCollection.ts
> +      id: String(collectionId),
Same as above

2022-10-25 23:35 UTC, rob-3 commented on web/src/pages/api/createCollection.ts
> +      // userId: String(session.user?.id),
as above

2022-10-25 23:35 UTC, rob-3 commented on web/src/pages/api/createCollection.ts
> +      name: String(query.name),
as above

2022-10-25 23:35 UTC, rob-3 commented on web/src/pages/api/removePostFromCollection.ts
> +  return res.json({ sucess: true });
`success`

2022-10-26 22:34 UTC, rob-3 commented
There's a couple of minor tweaks I'm gonna make, but they're pretty minor so I'll just add them and get this merged tonight. Good work

2022-10-26 22:43 UTC, rob-3 commented
Eh, it's fine actually - approved

2022-10-26 22:43 UTC, rob-3 approved these changes

2022-10-28 13:21 UTC, merged